language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script:
  - ./bin/rake db:migrate RAILS_ENV=test
  - ./bin/rspec
before_install:
  - "export BUNDLE_JOBS=4"
  - "export COVERAGE=true"
  - "export COVERALLS=true"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
bundler_args: --without development --deployment
cache:
  - bundler
  - apt
