language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
script:
  - ./bin/rake db:migrate RAILS_ENV=test
  - ./bin/rspec
before_install:
  - "sh -e /etc/init.d/xvfb start"
after_failure:
  - "./script/share_images.sh"
bundler_args: --without development --deployment --jobs 4
cache: bundler
sudo: false
env:
  global:
      - COVERAGE=true
      - CODECLIMATE_REPO_TOKEN=fa7ed59cc6227b968e7e3bb14ffd71b8ac11bf67b349286d1ce87edefc574ebe
      - DISPLAY=:99.0
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      
